/*
 * PRApp  Copyright (C) 2019  Luca Bartolomei
 *
 * This file is part of PRApp.
 *
 *     PRApp is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     PRApp is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with PRApp.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.prapp.model.net.enums;

public enum Comando {

    COMANDO_INDEFINITO(-1),

    COMANDO_UTENTE_REGISTRAZIONE(1),
    COMANDO_UTENTE_LOGIN(2),
    COMANDO_UTENTE_LOGOUT(3),
    COMANDO_UTENTE_CREA_STAFF(4),
    COMANDO_UTENTE_ACCEDI_STAFF(5),
    COMANDO_UTENTE_RESTITUISCI_LISTA_STAFF(6),
    COMANDO_UTENTE_RESTITUISCI_LISTA_STAFF_MEMBRI(7),
    COMANDO_UTENTE_RENEW_TOKEN(8),
    COMANDO_UTENTE_GET_TOKEN(9),
    COMANDO_UTENTE_LOGIN_TOKEN(10),

    COMANDO_MEMBRO_RESTITUISCI_LISTA_UTENTI(102),
    COMANDO_MEMBRO_RESTITUISCI_DIRITTI_PERSONALI(103),
    COMANDO_MEMBRO_RESTITUISCI_DIRITTI_UTENTE(104),
    COMANDO_MEMBRO_RESTITUISCI_LISTA_EVENTI(105),
    COMANDO_MEMBRO_RESTITUISCI_TIPI_PREVENDITA(106),
    COMANDO_MEMBRO_RESTITUISCI_LISTA_CLIENTI(107),

    COMANDO_PR_AGGIUNGI_CLIENTE(202),
    COMANDO_PR_AGGIUNGI_PREVENDITA(203),
    COMANDO_PR_MODIFICA_PREVENDITA(204),
    COMANDO_PR_RESTITUISCI_PREVENDITE(205),
    COMANDO_PR_RESTITUISCI_STATISTICHE_PR_TOTALI(206),
    COMANDO_PR_RESTITUISCI_STATISTICHE_PR_STAFF(207),
    COMANDO_PR_RESTITUISCI_STATISTICHE_PR_EVENTO(208),

    COMANDO_CASSIERE_TIMBRA_ENTRATA(302),
    COMANDO_CASSIERE_RESTITUISCI_DATI_CLIENTE(303),
    COMANDO_CASSIERE_RESTITUISCI_STATISTICHE_CASSIERE_TOTALI(304),
    COMANDO_CASSIERE_RESTITUISCI_STATISTICHE_CASSIERE_STAFF(305),
    COMANDO_CASSIERE_RESTITUISCI_STATISTICHE_CASSIERE_EVENTO(306),
    COMANDO_CASSIERE_RESTITUISCI_ENTRATE_SVOLTE(307),
    COMANDO_CASSIERE_RESTITUISCI_PREVENDITE_EVENTO(308),
    COMANDO_CASSIERE_RESTITUISCI_INFORMAZIONI_PREVENDITA(309),
    COMANDO_CASSIERE_RESTITUISCI_LISTA_PREVENDITE_TIMBRATE(310),
    COMANDO_CASSIERE_RESTITUISCI_LISTA_PREVENDITE_NON_TIMBRATE(311),

    COMANDO_AMMINISTRATORE_RIMUOVI_CLIENTE(402),
    COMANDO_AMMINISTRATORE_AGGIUNGI_EVENTO(403),
    COMANDO_AMMINISTRATORE_MODIFICA_EVENTO(404),
    COMANDO_AMMINISTRATORE_AGGIUNGI_TIPO_PREVENDITA(405),
    COMANDO_AMMINISTRATORE_MODIFICA_TIPO_PREVENDITA(406),
    COMANDO_AMMINISTRATORE_ELIMINA_TIPO_PREVENDITA(407),
    COMANDO_AMMINISTRATORE_MODIFICA_DIRITTI_UTENTE(408),
    COMANDO_AMMINISTRATORE_RESTITUISCI_STATISTICHE_PR(409),
    COMANDO_AMMINISTRATORE_RESTITUISCI_STATISTICHE_CASSIERE(410),
    COMANDO_AMMINISTRATORE_RESTITUISCI_STATISTICHE_EVENTO(411),
    COMANDO_AMMINISTRATORE_RESTITUISCI_PREVENDITE(412),
    COMANDO_AMMINISTRATORE_RIMUOVI_MEMBRO(413),
    COMANDO_AMMINISTRATORE_MODIFICA_CODICE_ACCESSO(414),
    COMANDO_AMMINISTRATORE_RESTITUISCI_STATISTICHE_PR_EVENTO(415),
    COMANDO_AMMINISTRATORE_RESTITUISCI_STATISTICHE_CASSIERE_EVENTO(416),

    COMANDO_MANUTENZIONE_ECHO(951),
    COMANDO_MANUTENZIONE_TIMESTAMP(952);

    public static Comando parseComando(int comando) {
        Comando[] values = Comando.values();

        for (Comando value: values) {
            if(value.getComando() == comando)
            {
                return value;
            }
        }

        return null;
    }

    private int comando;

    private Comando(int comando) {this.comando = comando;}

    public int getComando() { return comando; }

}
